- name: Wait for SonarQube to begin answering requests
  uri:
    url: '{{ sonarqube_url }}/'
    return_content: yes
    validate_certs: no
  register: sonarqube_index
  until: '"doctype html" in sonarqube_index.content'
  retries: 30
  delay: 5

- name: Create ploigos service account
  shell: >-
    devsecops-api sonarqube add-user
    {{ sonarqube_url }}
    --login-username '{{ sonarqube_username }}' --login-password '{{ sonarqube_password }}'
    --usernames '{{ ploigos_service_account.username }}'
    --passwords '{{ ploigos_service_account.password }}'
  register: sonarqube_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: sonarqube_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: sonarqube_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or sonarqube_users.rc != 0
  until: not sonarqube_users.failed
  retries: 3
  delay: 10
