---
- name: Grant argocd-application-controller serviceaccount cluster-admin
  k8s:
    api_key: "{{ argocd_k8s_token }}"
    host: "{{ argocd_k8s_api }}"
    validate_certs: false
    definition: "{{ lookup('template', 'cluster-role-binding.yml.j2') }}"

- name: Create ploigos service account
  k8s:
    api_key: "{{ argocd_k8s_token }}"
    host: "{{ argocd_k8s_api }}"
    validate_certs: false
    namespace: '{{ argocd_project_name }}'
    definition: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ argocd_cr_name }}-cm
      data:
        'accounts.{{ ploigos_service_account.username }}': 'apiKey, login'

- name: Get ArgoCD admin password
  k8s_info:
    api_key: "{{ argocd_k8s_token }}"
    host: "{{ argocd_k8s_api }}"
    validate_certs: false
    api_version: v1
    kind: Secret
    namespace: '{{ argocd_project_name }}'
    name: "{{ argocd_cr_name }}-cluster"
  register: argocd_cluster_secret

- set_fact:
    argocd_admin_password: "{{ argocd_cluster_secret.resources[0].data['admin.password'] | b64decode }}"

- name: Get ArgoCD server pod
  k8s_info:
    api_key: "{{ argocd_k8s_token }}"
    host: "{{ argocd_k8s_api }}"
    validate_certs: false
    api_version: v1
    kind: Pod
    namespace: '{{ argocd_project_name }}'
    label_selectors:
    - "app.kubernetes.io/name={{ argocd_cr_name }}-server"
  register: argocd_pod

- name: Set ploigos service account password
  community.kubernetes.k8s_exec:
    api_key: "{{ argocd_k8s_token }}"
    host: "{{ argocd_k8s_api }}"
    validate_certs: false
    namespace: '{{ argocd_project_name }}'
    pod: '{{ argocd_pod.resources[0].metadata.name }}'
    command: sh -c "argocd login {{ argocd_cr_name }}-server.{{ argocd_project_name }}.svc.cluster.local --username=admin --password={{ argocd_admin_password }} --insecure --config config && argocd account update-password --account={{ ploigos_service_account.username }} --new-password={{ ploigos_service_account.password }} --current-password={{ argocd_admin_password }} --config config && rm -f config"
