- name: Wait for Quay route to begin answering requests
  uri:
    url: 'https://{{ quay_url }}/'
    return_content: yes
    validate_certs: no
  register: quay_index
  until: '"DOCTYPE html" in quay_index.content'
  retries: 10
  delay: 30

- name: Add ploigos service account to Quay instance
  shell: >-
    devsecops-api quay add-user https://{{ quay_url }}
    --login-username {{ quay_username }} --login-password {{ quay_password }}
    --usernames '{{ ploigos_service_account.username }}'
    --passwords '{{ ploigos_service_account.password }}'
  register: quay_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Create Organization for pipeline
  shell: >-
    devsecops-api quay add-org https://{{ quay_url }}
    --login-username '{{ ploigos_service_account.username }}' --login-password '{{ ploigos_service_account.password }}'
    --organizations platform
  register: quay_orgs
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_orgs.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Create Robot account
  shell: >-
    devsecops-api quay add-robot https://{{ quay_url }}
    --login-username '{{ ploigos_service_account.username }}' --login-password '{{ ploigos_service_account.password }}'
    --organization platform --robot-name '{{ ploigos_service_account.username }}' --robot-description 'Ploigos Platform Robot Account'
  register: quay_robot
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_robot.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Get robot token
  set_fact:
    quay_robot_token: "{{ quay_robot.stdout | regex_search('[A-Z0-9]{64}') }}"

- name: Construct docker auth object
  set_fact:
    quay_robot_docker_config: "{{ lookup('template', 'quay-docker-config.yml.j2') | from_yaml | to_json }}"

- name: Store Quay robot token 
    block:
    # Create a Secret to hold the Robot pull sec if this role is run by
    # the operator.
    - name: Create Quay robot token secret
      k8s:
        definition: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: quay-robot-token
            namespace: '{{ ploigos_namespace }}'
          data:
            .dockerconfigjson: '{{ quay_robot_docker_config | b64encode }}'
          type: kubernetes.io/dockerconfigjson
      rescue:
      - name: Print pull secret to stdout
        debug:
          msg: |
            ROBOT PULL SECRET: {{ quay_robot_docker_config }}

            Be sure to save this- you'll need it later :-)
