- name: Add ploigos chart repo
  community.kubernetes.helm_repository:
    name: ploigos_charts
    repo_url: "{{ ploigos_platform.helm_repository }}"

- name: Deploy cluster resources chart
  community.kubernetes.helm:
    api_key: "{{ tekton_k8s_token }}"
    host: "{{ tekton_k8s_api }}"
    validate_certs: false
    name: ploigos-workflow-tekton-cluster-resources
    chart_ref: ploigos_charts/ploigos-workflow-tekton-cluster-resources
    values: "{{ lookup('template', 'ploigos-cluster-chart-values.yaml.j2') | from_yaml }}"
    release_namespace: "{{ tekton_namespace }}"
    release_state: "{{ tekton_chart_state }}"
  register: cluster_resources_chart
  ignore_errors: true
